<?php

namespace App\Http\Controllers;

use App\Ballon;
use App\Blob;
use App\Circle_member;
use App\Comment;
use App\High_education;
use App\Knock;
use App\Language;
use App\obj;
use App\Privacy_preset;
use App\Reaction;
use App\Reply;
use App\User;
use App\UserAddress;
use Illuminate\Http\Request;

class DevController extends Controller {
	public function resetKnocks(Request $request) {
		//Delet Ballons & their Objects
		Ballon::truncate();
		//Delete Reactions & their Objects
		Reaction::truncate();
		//Delete Replies & their Objects
		$reply = Reply::all();
		foreach ($reply as $rep) {
			$rep->delete();
		}

		//Delete Comments & their Objects
		$comment = Comment::all();
		foreach ($comment as $rep) {
			$rep->delete();
		}

		//Delete Blobs & their Objects
		Blob::truncate();
		//Delete Knocks & their Objects
		$knock = Knock::all();
		foreach ($knock as $rep) {
			$rep->delete();
		}

		return 'done';

	}

	public function resetUsers(Request $request) {
		//Delet Ballons & their Objects
		Ballon::truncate();
		//Delete Reactions & their Objects
		Reaction::truncate();
		//Delete Replies & their Objects
		$reply = Reply::all();
		foreach ($reply as $rep) {
			$rep->delete();
		}

		//Delete Comments & their Objects
		$comment = Comment::all();
		foreach ($comment as $rep) {
			$rep->delete();
		}

		//Delete Blobs & their Objects
		Blob::truncate();
		//Delete Knocks & their Objects
		$knock = Knock::all();
		foreach ($knock as $rep) {
			$rep->delete();
		}

		$object = obj::all();
		foreach ($object as $rep) {
			$rep->delete();
		}

		$user = User::all();
		foreach ($user as $rep) {
			$rep->delete();
		}

		return 'done';

	}

	public function reinstall(Request $request) {
		$v = new Privacy_preset();
		$v->name = 'valid';
		$v->save();

		$v = new Privacy_preset();
		$v->name = 'invalid';
		$v->save();

		$v = new Privacy_preset();
		$v->name = 'invalid_for_all';
		$v->save();

		$v = new Language();
		$v->name = 'en';
		$v->alignment = 'left';
		$v->font_family = 'titillium';
		$v->display_name = 'English';
		$v->save();

		$v = new Language();
		$v->name = 'ar-sa';
		$v->alignment = 'right';
		$v->font_family = 'cairo';
		$v->display_name = 'لاعربيه';
		$v->save();

		return 'done';
	}

	public function removeAllFriends(Request $request) {
		$mems = Circle_member::all();
		foreach ($mems as $mem) {
			$mem->delete();
		}

		return 'done';
	}

	public function watchMembershipDublications() {
		$allUsers = User::all();
		$removed = 0;
		$mainCounter = 0;
		foreach ($allUsers as $user) {
			$friends = $user->friends();
			$mainCircle = $user->mainCircle()->id;
			foreach ($friends as $friend) {
				$c = $friends->where('user_id', '=', $user->id);
				if ($c->count() > 1) {
					$mainCounter += $c->count() - 1;
					$c->first()->delete();
					$removed++;
				}
			}
		}
		return array('found' => $mainCounter, 'removed' => $removed);
	}
	public function addRandomEntry(Request $request) {
		$users = User::all();
		//Data Sources
		$countries = [
			"AD",
			"AE",
			"AF",
			"AG",
			"AI",
			"AL",
			"AM",
			"AO",
			"AQ",
			"AR",
			"AS",
			"AT",
			"AU",
			"AW",
			"AX",
			"AZ",
			"BA",
			"BB",
			"BD",
			"BE",
			"BF",
			"BG",
			"BH",
			"BI",
			"BJ",
			"BL",
			"BM",
			"BN",
			"BO",
			"BQ",
			"BR",
			"BS",
			"BT",
			"BV",
			"BW",
			"BY",
			"BZ",
			"CA",
			"CC",
			"CD",
			"CF",
			"CG",
			"CH",
			"CI",
			"CK",
			"CL",
			"CM",
			"CN",
			"CO",
			"CR",
			"CU",
			"CV",
			"CW",
			"CX",
			"CY",
			"CZ",
			"DE",
			"DJ",
			"DK",
			"DM",
			"DO",
			"DZ",
			"EC",
			"EE",
			"EG",
			"EH",
			"ER",
			"ES",
			"ET",
			"FI",
			"FJ",
			"FK",
			"FM",
			"FO",
			"FR",
			"GA",
			"GB",
			"GD",
			"GE",
			"GF",
			"GG",
			"GH",
			"GI",
			"GL",
			"GM",
			"GN",
			"GP",
			"GQ",
			"GR",
			"GS",
			"GT",
			"GU",
			"GW",
			"GY",
			"HK",
			"HM",
			"HN",
			"HR",
			"HT",
			"HU",
			"ID",
			"IE",
			"IL",
			"IM",
			"IN",
			"IO",
			"IQ",
			"IR",
			"IS",
			"IT",
			"JE",
			"JM",
			"JO",
			"JP",
			"KE",
			"KG",
			"KH",
			"KI",
			"KM",
			"KN",
			"KP",
			"KR",
			"KW",
			"KY",
			"KZ",
			"LA",
			"LB",
			"LC",
			"LI",
			"LK",
			"LR",
			"LS",
			"LT",
			"LU",
			"LV",
			"LY",
			"MA",
			"MC",
			"MD",
			"ME",
			"MF",
			"MG",
			"MH",
			"MK",
			"ML",
			"MM",
			"MN",
			"MO",
			"MP",
			"MQ",
			"MR",
			"MS",
			"MT",
			"MU",
			"MV",
			"MW",
			"MX",
			"MY",
			"MZ",
			"NA",
			"NC",
			"NE",
			"NF",
			"NG",
			"NI",
			"NL",
			"NO",
			"NP",
			"NR",
			"NU",
			"NZ",
			"OM",
			"PA",
			"PE",
			"PF",
			"PG",
			"PH",
			"PK",
			"PL",
			"PM",
			"PN",
			"PR",
			"PS",
			"PT",
			"PW",
			"PY",
			"QA",
			"RE",
			"RO",
			"RS",
			"RU",
			"RW",
			"SA",
			"SB",
			"SC",
			"SD",
			"SE",
			"SG",
			"SH",
			"SI",
			"SJ",
			"SK",
			"SL",
			"SM",
			"SN",
			"SO",
			"SR",
			"SS",
			"ST",
			"SV",
			"SX",
			"SY",
			"SZ",
			"TC",
			"TD",
			"TF",
			"TG",
			"TH",
			"TJ",
			"TK",
			"TL",
			"TM",
			"TN",
			"TO",
			"TR",
			"TT",
			"TV",
			"TW",
			"TZ",
			"UA",
			"UG",
			"UM",
			"US",
			"UY",
			"UZ",
			"VA",
			"VC",
			"VE",
			"VG",
			"VI",
			"VN",
			"VU",
			"WF",
			"WS",
			"XK",
			"YE",
			"YT",
			"ZA",
			"ZM",
			"ZW",
		];
		$states = [
			'Alabama',
			'Alaska',
			'Arizona',
			'Arkansas',
			'California',
			'Colorado',
			'Connecticut',
			'Delaware',
			'Florida',
			'Georgia',
			'Hawaii',
			'Idaho',
			'IllinoisIndiana',
			'Iowa',
			'Kansas',
			'Kentucky',
			'Louisiana',
			'Maine',
			'Maryland',
			'Massachusetts',
			'Michigan',
			'Minnesota',
			'Mississippi',
			'Missouri',
			'MontanaNebraska',
			'Nevada',
			'NewHampshire',
			'NewJersey',
			'NewMexico',
			'NewYork',
			'NorthCarolina',
			'NorthDakota',
			'Ohio',
			'Oklahoma',
			'Oregon',
			'PennsylvaniaRhodeIsland',
			'SouthCarolina',
			'SouthDakota',
			'Tennessee',
			'Texas',
			'Utah',
			'Vermont',
			'Virginia',
			'Washington',
			'WestVirginia',
			'Wisconsin',
			'Wyoming',
		];
		$cities = [
			'Alexander City',
			'Andalusia',
			'Anniston',
			'Athens',
			'Atmore',
			'Auburn',
			'Bessemer',
			'Birmingham',
			'Chickasaw',
			'Clanton',
			'Cullman',
			'Decatur',
			'Demopolis',
			'Dothan',
			'Enterprise',
			'Eufaula',
			'Florence',
			'Fort Payne',
			'Gadsden',
			'Greenville',
			'Guntersville',
			'Huntsville',
			'Jasper',
			'Marion',
			'Mobile',
			'Montgomery',
			'Opelika',
			'Ozark',
			'Phenix City',
			'Prichard',
			'Scottsboro',
			'Selma',
			'Sheffield',
			'Sylacauga',
			'Talladega',
			'Troy',
			'Tuscaloosa',
			'Tuscumbia',
			'Tuskegee',
			'Alaska',
			'Anchorage',
			'Cordova',
			'Fairbanks',
			'Haines',
			'Homer',
			'Juneau',
			'Ketchikan',
			'Kodiak',
			'Kotzebue',
			'Nome',
			'Palmer',
			'Seward',
			'Sitka',
			'Skagway',
			'Valdez',
			'Arizona',
			'Ajo',
			'Avondale',
			'Bisbee',
			'Casa Grande',
			'Chandler',
			'Clifton',
			'Douglas',
			'Flagstaff',
			'Florence',
			'Gila Bend',
			'Glendale',
			'Globe',
			'Kingman',
			'Lake Havasu City',
			'Mesa',
			'Nogales',
			'Oraibi',
			'Phoenix',
			'Prescott',
			'Scottsdale',
			'Sierra Vista',
			'Tempe',
			'Tombstone',
			'Tucson',
			'Walpi',
			'Window Rock',
			'Winslow',
			'Yuma',
			'Arkansas',
			'Arkadelphia',
			'Arkansas Post',
			'Batesville',
			'Benton',
			'Blytheville',
			'Camden',
			'Conway',
			'Crossett',
			'El Dorado',
			'Fayetteville',
			'Forrest City',
			'Fort Smith',
			'Harrison',
			'Helena',
			'Hope',
			'Hot Springs',
			'Jacksonville',
			'Jonesboro',
			'Little Rock',
			'Magnolia',
			'Morrilton',
			'Newport',
			'North Little Rock',
			'Osceola',
			'Pine Bluff',
			'Rogers',
			'Searcy',
			'Stuttgart',
			'Van Buren',
			'West Memphis',
			'California',
			'Alameda',
			'Alhambra',
			'Anaheim',
			'Antioch',
			'Arcadia',
			'Bakersfield',
			'Barstow',
			'Belmont',
			'Berkeley',
			'Beverly Hills',
			'Brea',
			'Buena Park',
			'Burbank',
			'Calexico',
			'Calistoga',
			'Carlsbad',
			'Carmel',
			'Chico',
			'Chula Vista',
			'Claremont',
			'Compton',
			'Concord',
			'Corona',
			'Coronado',
			'Costa Mesa',
			'Culver City',
			'Daly City',
			'Davis',
			'Downey',
			'El Centro',
			'El Cerrito',
			'El Monte',
			'Escondido',
			'Eureka',
			'Fairfield',
			'Fontana',
			'Fremont',
			'Fresno',
			'Fullerton',
			'Garden Grove',
			'Glendale',
			'Hayward',
			'Hollywood',
			'Huntington Beach',
			'Indio',
			'Inglewood',
			'Irvine',
			'La Habra',
			'Laguna Beach',
			'Lancaster',
			'Livermore',
			'Lodi',
			'Lompoc',
			'Long Beach',
			'Los Angeles',
			'Malibu',
			'Martinez',
			'Marysville',
			'Menlo Park',
			'Merced',
			'Modesto',
			'Monterey',
			'Mountain View',
			'Napa',
			'Needles',
			'Newport Beach',
			'Norwalk',
			'Novato',
			'Oakland',
			'Oceanside',
			'Ojai',
			'Ontario',
			'Orange',
			'Oroville',
			'Oxnard',
			'Pacific Grove',
			'Palm Springs',
			'Palmdale',
			'Palo Alto',
			'Pasadena',
			'Petaluma',
			'Pomona',
			'Port Hueneme',
			'Rancho Cucamonga',
			'Red Bluff',
			'Redding',
			'Redlands',
			'Redondo Beach',
			'Redwood City',
			'Richmond',
			'Riverside',
			'Roseville',
			'Sacramento',
			'Salinas',
			'San Bernardino',
			'San Clemente',
			'San Diego',
			'San Fernando',
			'San Francisco',
			'San Gabriel',
			'San Jose',
			'San Juan Capistrano',
			'San Leandro',
			'San Luis Obispo',
			'San Marino',
			'San Mateo',
			'San Pedro',
			'San Rafael',
			'San Simeon',
			'Santa Ana',
			'Santa Barbara',
			'Santa Clara',
			'Santa Clarita',
			'Santa Cruz',
			'Santa Monica',
			'Santa Rosa',
			'Sausalito',
			'Simi Valley',
			'Sonoma',
			'South San Francisco',
			'Stockton',
			'Sunnyvale',
			'Susanville',
			'Thousand Oaks',
			'Torrance',
			'Turlock',
			'Ukiah',
			'Vallejo',
			'Ventura',
			'Victorville',
			'Visalia',
			'Walnut Creek',
			'Watts',
			'West Covina',
			'Whittier',
			'Woodland',
			'Yorba Linda',
			'Yuba City',
			'Colorado',
			'Alamosa',
			'Aspen',
			'Aurora',
			'Boulder',
			'Breckenridge',
			'Brighton',
			'Canon City',
			'Central City',
			'Climax',
			'Colorado Springs',
			'Cortez',
			'Cripple Creek',
			'Denver',
			'Durango',
			'Englewood',
			'Estes Park',
			'Fort Collins',
			'Fort Morgan',
			'Georgetown',
			'Glenwood Springs',
			'Golden',
			'Grand Junction',
			'Greeley',
			'Gunnison',
			'La Junta',
			'Leadville',
			'Littleton',
			'Longmont',
			'Loveland',
			'Montrose',
			'Ouray',
			'Pagosa Springs',
			'Pueblo',
			'Silverton',
			'Steamboat Springs',
			'Sterling',
			'Telluride',
			'Trinidad',
			'Vail',
			'Walsenburg',
			'Westminster',
			'Connecticut',
			'Ansonia',
			'Berlin',
			'Bloomfield',
			'Branford',
			'Bridgeport',
			'Bristol',
			'Coventry',
			'Danbury',
			'Darien',
			'Derby',
			'East Hartford',
			'East Haven',
			'Enfield',
			'Fairfield',
			'Farmington',
			'Greenwich',
			'Groton',
			'Guilford',
			'Hamden',
			'Hartford',
			'Lebanon',
			'Litchfield',
			'Manchester',
			'Mansfield',
			'Meriden',
			'Middletown',
			'Milford',
			'Mystic',
			'Naugatuck',
			'New Britain',
			'New Haven',
			'New London',
			'North Haven',
			'Norwalk',
			'Norwich',
			'Old Saybrook',
			'Orange',
			'Seymour',
			'Shelton',
			'Simsbury',
			'Southington',
			'Stamford',
			'Stonington',
			'Stratford',
			'Torrington',
			'Wallingford',
			'Waterbury',
			'Waterford',
			'Watertown',
			'West Hartford',
			'West Haven',
			'Westport',
			'Wethersfield',
			'Willimantic',
			'Windham',
			'Windsor',
			'Windsor Locks',
			'Winsted',
			'Delaware',
			'Dover',
			'Lewes',
			'Milford',
			'New Castle',
			'Newark',
			'Smyrna',
			'Wilmington',
			'Florida',
			'Apalachicola',
			'Bartow',
			'Belle Glade',
			'Boca Raton',
			'Bradenton',
			'Cape Coral',
			'Clearwater',
			'Cocoa Beach',
			'Cocoa-Rockledge',
			'Coral Gables',
			'Daytona Beach',
			'De Land',
			'Deerfield Beach',
			'Delray Beach',
			'Fernandina Beach',
			'Fort Lauderdale',
			'Fort Myers',
			'Fort Pierce',
			'Fort Walton Beach',
			'Gainesville',
			'Hallandale Beach',
			'Hialeah',
			'Hollywood',
			'Homestead',
			'Jacksonville',
			'Key West',
			'Lake City',
			'Lake Wales',
			'Lakeland',
			'Largo',
			'Melbourne',
			'Miami',
			'Miami Beach',
			'Naples',
			'New Smyrna Beach',
			'Ocala',
			'Orlando',
			'Ormond Beach',
			'Palatka',
			'Palm Bay',
			'Palm Beach',
			'Panama City',
			'Pensacola',
			'Pompano Beach',
			'Saint Augustine',
			'Saint Petersburg',
			'Sanford',
			'Sarasota',
			'Sebring',
			'Tallahassee',
			'Tampa',
			'Tarpon Springs',
			'Titusville',
			'Venice',
			'West Palm Beach',
			'White Springs',
			'Winter Haven',
			'Winter Park',
			'Georgia',
			'Albany',
			'Americus',
			'Andersonville',
			'Athens',
			'Atlanta',
			'Augusta',
			'Bainbridge',
			'Blairsville',
			'Brunswick',
			'Calhoun',
			'Carrollton',
			'Columbus',
			'Dahlonega',
			'Dalton',
			'Darien',
			'Decatur',
			'Douglas',
			'East Point',
			'Fitzgerald',
			'Fort Valley',
			'Gainesville',
			'La Grange',
			'Macon',
			'Marietta',
			'Milledgeville',
			'Plains',
			'Rome',
			'Savannah',
			'Toccoa',
			'Valdosta',
			'Warm Springs',
			'Warner Robins',
			'Washington',
			'Waycross',
			'Hawaii',
			'Hanalei',
			'Hilo',
			'Honaunau',
			'Honolulu',
			'Kahului',
			'Kaneohe',
			'Kapaa',
			'Kawaihae',
			'Lahaina',
			'Laie',
			'Wahiawa',
			'Wailuku',
			'Waimea',
			'Idaho',
			'Blackfoot',
			'Boise',
			'Bonners Ferry',
			'Caldwell',
			'Coeur d’Alene',
			'Idaho City',
			'Idaho Falls',
			'Kellogg',
			'Lewiston',
			'Moscow',
			'Nampa',
			'Pocatello',
			'Priest River',
			'Rexburg',
			'Sun Valley',
			'Twin Falls',
			'Illinois',
			'Alton',
			'Arlington Heights',
			'Arthur',
			'Aurora',
			'Belleville',
			'Belvidere',
			'Bloomington',
			'Brookfield',
			'Cahokia',
			'Cairo',
			'Calumet City',
			'Canton',
			'Carbondale',
			'Carlinville',
			'Carthage',
			'Centralia',
			'Champaign',
			'Charleston',
			'Chester',
			'Chicago',
			'Chicago Heights',
			'Cicero',
			'Collinsville',
			'Danville',
			'Decatur',
			'DeKalb',
			'Des Plaines',
			'Dixon',
			'East Moline',
			'East Saint Louis',
			'Effingham',
			'Elgin',
			'Elmhurst',
			'Evanston',
			'Freeport',
			'Galena',
			'Galesburg',
			'Glen Ellyn',
			'Glenview',
			'Granite City',
			'Harrisburg',
			'Herrin',
			'Highland Park',
			'Jacksonville',
			'Joliet',
			'Kankakee',
			'Kaskaskia',
			'Kewanee',
			'La Salle',
			'Lake Forest',
			'Libertyville',
			'Lincoln',
			'Lisle',
			'Lombard',
			'Macomb',
			'Mattoon',
			'Moline',
			'Monmouth',
			'Mount Vernon',
			'Mundelein',
			'Naperville',
			'Nauvoo',
			'Normal',
			'North Chicago',
			'Oak Park',
			'Oregon',
			'Ottawa',
			'Palatine',
			'Park Forest',
			'Park Ridge',
			'Pekin',
			'Peoria',
			'Petersburg',
			'Pontiac',
			'Quincy',
			'Rantoul',
			'River Forest',
			'Rock Island',
			'Rockford',
			'Salem',
			'Shawneetown',
			'Skokie',
			'South Holland',
			'Springfield',
			'Streator',
			'Summit',
			'Urbana',
			'Vandalia',
			'Virden',
			'Waukegan',
			'Wheaton',
			'Wilmette',
			'Winnetka',
			'Wood River',
			'Zion',
			'Indiana',
			'Anderson',
			'Bedford',
			'Bloomington',
			'Columbus',
			'Connersville',
			'Corydon',
			'Crawfordsville',
			'East Chicago',
			'Elkhart',
			'Elwood',
			'Evansville',
			'Fort Wayne',
			'French Lick',
			'Gary',
			'Geneva',
			'Goshen',
			'Greenfield',
			'Hammond',
			'Hobart',
			'Huntington',
			'Indianapolis',
			'Jeffersonville',
			'Kokomo',
			'Lafayette',
			'Madison',
			'Marion',
			'Michigan City',
			'Mishawaka',
			'Muncie',
			'Nappanee',
			'Nashville',
			'New Albany',
			'New Castle',
			'New Harmony',
			'Peru',
			'Plymouth',
			'Richmond',
			'Santa Claus',
			'Shelbyville',
			'South Bend',
			'Terre Haute',
			'Valparaiso',
			'Vincennes',
			'Wabash',
			'West Lafayette',
			'Iowa',
			'Amana Colonies',
			'Ames',
			'Boone',
			'Burlington',
			'Cedar Falls',
			'Cedar Rapids',
			'Charles City',
			'Cherokee',
			'Clinton',
			'Council Bluffs',
			'Davenport',
			'Des Moines',
			'Dubuque',
			'Estherville',
			'Fairfield',
			'Fort Dodge',
			'Grinnell',
			'Indianola',
			'Iowa City',
			'Keokuk',
			'Mason City',
			'Mount Pleasant',
			'Muscatine',
			'Newton',
			'Oskaloosa',
			'Ottumwa',
			'Sioux City',
			'Waterloo',
			'Webster City',
			'West Des Moines',
			'Kansas',
			'Abilene',
			'Arkansas City',
			'Atchison',
			'Chanute',
			'Coffeyville',
			'Council Grove',
			'Dodge City',
			'Emporia',
			'Fort Scott',
			'Garden City',
			'Great Bend',
			'Hays',
			'Hutchinson',
			'Independence',
			'Junction City',
			'Kansas City',
			'Lawrence',
			'Leavenworth',
			'Liberal',
			'Manhattan',
			'McPherson',
			'Medicine Lodge',
			'Newton',
			'Olathe',
			'Osawatomie',
			'Ottawa',
			'Overland Park',
			'Pittsburg',
			'Salina',
			'Shawnee',
			'Smith Center',
			'Topeka',
			'Wichita',
			'Kentucky',
			'Ashland',
			'Barbourville',
			'Bardstown',
			'Berea',
			'Boonesborough',
			'Bowling Green',
			'Campbellsville',
			'Covington',
			'Danville',
			'Elizabethtown',
			'Frankfort',
			'Harlan',
			'Harrodsburg',
			'Hazard',
			'Henderson',
			'Hodgenville',
			'Hopkinsville',
			'Lexington',
			'Louisville',
			'Mayfield',
			'Maysville',
			'Middlesboro',
			'Newport',
			'Owensboro',
			'Paducah',
			'Paris',
			'Richmond',
			'Louisiana',
			'Abbeville',
			'Alexandria',
			'Bastrop',
			'Baton Rouge',
			'Bogalusa',
			'Bossier City',
			'Gretna',
			'Houma',
			'Lafayette',
			'Lake Charles',
			'Monroe',
			'Morgan City',
			'Natchitoches',
			'New Iberia',
			'New Orleans',
			'Opelousas',
			'Ruston',
			'Saint Martinville',
			'Shreveport',
			'Thibodaux',
			'Maine',
			'Auburn',
			'Augusta',
			'Bangor',
			'Bar Harbor',
			'Bath',
			'Belfast',
			'Biddeford',
			'Boothbay Harbor',
			'Brunswick',
			'Calais',
			'Caribou',
			'Castine',
			'Eastport',
			'Ellsworth',
			'Farmington',
			'Fort Kent',
			'Gardiner',
			'Houlton',
			'Kennebunkport',
			'Kittery',
			'Lewiston',
			'Lubec',
			'Machias',
			'Orono',
			'Portland',
			'Presque Isle',
			'Rockland',
			'Rumford',
			'Saco',
			'Scarborough',
			'Waterville',
			'York',
			'Maryland',
			'Aberdeen',
			'Annapolis',
			'Baltimore',
			'Bethesda-Chevy Chase',
			'Bowie',
			'Cambridge',
			'Catonsville',
			'College Park',
			'Columbia',
			'Cumberland',
			'Easton',
			'Elkton',
			'Emmitsburg',
			'Frederick',
			'Greenbelt',
			'Hagerstown',
			'Hyattsville',
			'Laurel',
			'Oakland',
			'Ocean City',
			'Rockville',
			'Saint Marys City',
			'Salisbury',
			'Silver Spring',
			'Takoma Park',
			'Towson',
			'Westminster',
			'Massachusetts',
			'Abington',
			'Adams',
			'Amesbury',
			'Amherst',
			'Andover',
			'Arlington',
			'Athol',
			'Attleboro',
			'Barnstable',
			'Bedford',
			'Beverly',
			'Boston',
			'Bourne',
			'Braintree',
			'Brockton',
			'Brookline',
			'Cambridge',
			'Canton',
			'Charlestown',
			'Chelmsford',
			'Chelsea',
			'Chicopee',
			'Clinton',
			'Cohasset',
			'Concord',
			'Danvers',
			'Dartmouth',
			'Dedham',
			'Dennis',
			'Duxbury',
			'Eastham',
			'Edgartown',
			'Everett',
			'Fairhaven',
			'Fall River',
			'Falmouth',
			'Fitchburg',
			'Framingham',
			'Gloucester',
			'Great Barrington',
			'Greenfield',
			'Groton',
			'Harwich',
			'Haverhill',
			'Hingham',
			'Holyoke',
			'Hyannis',
			'Ipswich',
			'Lawrence',
			'Lenox',
			'Leominster',
			'Lexington',
			'Lowell',
			'Ludlow',
			'Lynn',
			'Malden',
			'Marblehead',
			'Marlborough',
			'Medford',
			'Milton',
			'Nahant',
			'Natick',
			'New Bedford',
			'Newburyport',
			'Newton',
			'North Adams',
			'Northampton',
			'Norton',
			'Norwood',
			'Peabody',
			'Pittsfield',
			'Plymouth',
			'Provincetown',
			'Quincy',
			'Randolph',
			'Revere',
			'Salem',
			'Sandwich',
			'Saugus',
			'Somerville',
			'South Hadley',
			'Springfield',
			'Stockbridge',
			'Stoughton',
			'Sturbridge',
			'Sudbury',
			'Taunton',
			'Tewksbury',
			'Truro',
			'Watertown',
			'Webster',
			'Wellesley',
			'Wellfleet',
			'West Bridgewater',
			'West Springfield',
			'Westfield',
			'Weymouth',
			'Whitman',
			'Williamstown',
			'Woburn',
			'Woods Hole',
			'Worcester',
			'Michigan',
			'Adrian',
			'Alma',
			'Ann Arbor',
			'Battle Creek',
			'Bay City',
			'Benton Harbor',
			'Bloomfield Hills',
			'Cadillac',
			'Charlevoix',
			'Cheboygan',
			'Dearborn',
			'Detroit',
			'East Lansing',
			'Eastpointe',
			'Ecorse',
			'Escanaba',
			'Flint',
			'Grand Haven',
			'Grand Rapids',
			'Grayling',
			'Grosse Pointe',
			'Hancock',
			'Highland Park',
			'Holland',
			'Houghton',
			'Interlochen',
			'Iron Mountain',
			'Ironwood',
			'Ishpeming',
			'Jackson',
			'Kalamazoo',
			'Lansing',
			'Livonia',
			'Ludington',
			'Mackinaw City',
			'Manistee',
			'Marquette',
			'Menominee',
			'Midland',
			'Monroe',
			'Mount Clemens',
			'Mount Pleasant',
			'Muskegon',
			'Niles',
			'Petoskey',
			'Pontiac',
			'Port Huron',
			'Royal Oak',
			'Saginaw',
			'Saint Ignace',
			'Saint Joseph',
			'Sault Sainte Marie',
			'Traverse City',
			'Trenton',
			'Warren',
			'Wyandotte',
			'Ypsilanti',
			'Minnesota',
			'Albert Lea',
			'Alexandria',
			'Austin',
			'Bemidji',
			'Bloomington',
			'Brainerd',
			'Crookston',
			'Duluth',
			'Ely',
			'Eveleth',
			'Faribault',
			'Fergus Falls',
			'Hastings',
			'Hibbing',
			'International Falls',
			'Little Falls',
			'Mankato',
			'Minneapolis',
			'Moorhead',
			'New Ulm',
			'Northfield',
			'Owatonna',
			'Pipestone',
			'Red Wing',
			'Rochester',
			'Saint Cloud',
			'Saint Paul',
			'Sauk Centre',
			'South Saint Paul',
			'Stillwater',
			'Virginia',
			'Willmar',
			'Winona',
			'Mississippi',
			'Bay Saint Louis',
			'Biloxi',
			'Canton',
			'Clarksdale',
			'Columbia',
			'Columbus',
			'Corinth',
			'Greenville',
			'Greenwood',
			'Grenada',
			'Gulfport',
			'Hattiesburg',
			'Holly Springs',
			'Jackson',
			'Laurel',
			'Meridian',
			'Natchez',
			'Ocean Springs',
			'Oxford',
			'Pascagoula',
			'Pass Christian',
			'Philadelphia',
			'Port Gibson',
			'Starkville',
			'Tupelo',
			'Vicksburg',
			'West Point',
			'Yazoo City',
			'Missouri',
			'Boonville',
			'Branson',
			'Cape Girardeau',
			'Carthage',
			'Chillicothe',
			'Clayton',
			'Columbia',
			'Excelsior Springs',
			'Ferguson',
			'Florissant',
			'Fulton',
			'Hannibal',
			'Independence',
			'Jefferson City',
			'Joplin',
			'Kansas City',
			'Kirksville',
			'Lamar',
			'Lebanon',
			'Lexington',
			'Maryville',
			'Mexico',
			'Monett',
			'Neosho',
			'New Madrid',
			'Rolla',
			'Saint Charles',
			'Saint Joseph',
			'Saint Louis',
			'Sainte Genevieve',
			'Salem',
			'Sedalia',
			'Springfield',
			'Warrensburg',
			'West Plains',
			'Montana',
			'Anaconda',
			'Billings',
			'Bozeman',
			'Butte',
			'Dillon',
			'Fort Benton',
			'Glendive',
			'Great Falls',
			'Havre',
			'Helena',
			'Kalispell',
			'Lewistown',
			'Livingston',
			'Miles City',
			'Missoula',
			'Virginia City',
			'Nebraska',
			'Beatrice',
			'Bellevue',
			'Boys Town',
			'Chadron',
			'Columbus',
			'Fremont',
			'Grand Island',
			'Hastings',
			'Kearney',
			'Lincoln',
			'McCook',
			'Minden',
			'Nebraska City',
			'Norfolk',
			'North Platte',
			'Omaha',
			'Plattsmouth',
			'Red Cloud',
			'Sidney',
			'Nevada',
			'Boulder City',
			'Carson City',
			'Elko',
			'Ely',
			'Fallon',
			'Genoa',
			'Goldfield',
			'Henderson',
			'Las Vegas',
			'North Las Vegas',
			'Reno',
			'Sparks',
			'Virginia City',
			'Winnemucca',
			'New Hampshire',
			'Berlin',
			'Claremont',
			'Concord',
			'Derry',
			'Dover',
			'Durham',
			'Exeter',
			'Franklin',
			'Hanover',
			'Hillsborough',
			'Keene',
			'Laconia',
			'Lebanon',
			'Manchester',
			'Nashua',
			'Peterborough',
			'Plymouth',
			'Portsmouth',
			'Rochester',
			'Salem',
			'Somersworth',
			'New Jersey',
			'Asbury Park',
			'Atlantic City',
			'Bayonne',
			'Bloomfield',
			'Bordentown',
			'Bound Brook',
			'Bridgeton',
			'Burlington',
			'Caldwell',
			'Camden',
			'Cape May',
			'Clifton',
			'Cranford',
			'East Orange',
			'Edison',
			'Elizabeth',
			'Englewood',
			'Fort Lee',
			'Glassboro',
			'Hackensack',
			'Haddonfield',
			'Hoboken',
			'Irvington',
			'Jersey City',
			'Lakehurst',
			'Lakewood',
			'Long Beach',
			'Long Branch',
			'Madison',
			'Menlo Park',
			'Millburn',
			'Millville',
			'Montclair',
			'Morristown',
			'Mount Holly',
			'New Brunswick',
			'New Milford',
			'Newark',
			'Ocean City',
			'Orange',
			'Parsippany–Troy Hills',
			'Passaic',
			'Paterson',
			'Perth Amboy',
			'Plainfield',
			'Princeton',
			'Ridgewood',
			'Roselle',
			'Rutherford',
			'Salem',
			'Somerville',
			'South Orange Village',
			'Totowa',
			'Trenton',
			'Union',
			'Union City',
			'Vineland',
			'Wayne',
			'Weehawken',
			'West New York',
			'West Orange',
			'Willingboro',
			'Woodbridge',
			'New Mexico',
			'Acoma',
			'Alamogordo',
			'Albuquerque',
			'Artesia',
			'Belen',
			'Carlsbad',
			'Clovis',
			'Deming',
			'Farmington',
			'Gallup',
			'Grants',
			'Hobbs',
			'Las Cruces',
			'Las Vegas',
			'Los Alamos',
			'Lovington',
			'Portales',
			'Raton',
			'Roswell',
			'Santa Fe',
			'Shiprock',
			'Silver City',
			'Socorro',
			'Taos',
			'Truth or Consequences',
			'Tucumcari',
			'New York',
			'Albany',
			'Amsterdam',
			'Auburn',
			'Babylon',
			'Batavia',
			'Beacon',
			'Bedford',
			'Binghamton',
			'Bronx',
			'Brooklyn',
			'Buffalo',
			'Chautauqua',
			'Cheektowaga',
			'Clinton',
			'Cohoes',
			'Coney Island',
			'Cooperstown',
			'Corning',
			'Cortland',
			'Crown Point',
			'Dunkirk',
			'East Aurora',
			'East Hampton',
			'Eastchester',
			'Elmira',
			'Flushing',
			'Forest Hills',
			'Fredonia',
			'Garden City',
			'Geneva',
			'Glens Falls',
			'Gloversville',
			'Great Neck',
			'Hammondsport',
			'Harlem',
			'Hempstead',
			'Herkimer',
			'Hudson',
			'Huntington',
			'Hyde Park',
			'Ilion',
			'Ithaca',
			'Jamestown',
			'Johnstown',
			'Kingston',
			'Lackawanna',
			'Lake Placid',
			'Levittown',
			'Lockport',
			'Mamaroneck',
			'Manhattan',
			'Massena',
			'Middletown',
			'Mineola',
			'Mount Vernon',
			'New Paltz',
			'New Rochelle',
			'New Windsor',
			'New York City',
			'Newburgh',
			'Niagara Falls',
			'North Hempstead',
			'Nyack',
			'Ogdensburg',
			'Olean',
			'Oneida',
			'Oneonta',
			'Ossining',
			'Oswego',
			'Oyster Bay',
			'Palmyra',
			'Peekskill',
			'Plattsburgh',
			'Port Washington',
			'Potsdam',
			'Poughkeepsie',
			'Queens',
			'Rensselaer',
			'Rochester',
			'Rome',
			'Rotterdam',
			'Rye',
			'Sag Harbor',
			'Saranac Lake',
			'Saratoga Springs',
			'Scarsdale',
			'Schenectady',
			'Seneca Falls',
			'Southampton',
			'Staten Island',
			'Stony Brook',
			'Stony Point',
			'Syracuse',
			'Tarrytown',
			'Ticonderoga',
			'Tonawanda',
			'Troy',
			'Utica',
			'Watertown',
			'Watervliet',
			'Watkins Glen',
			'West Seneca',
			'White Plains',
			'Woodstock',
			'Yonkers',
			'North Carolina',
			'Asheboro',
			'Asheville',
			'Bath',
			'Beaufort',
			'Boone',
			'Burlington',
			'Chapel Hill',
			'Charlotte',
			'Concord',
			'Durham',
			'Edenton',
			'Elizabeth City',
			'Fayetteville',
			'Gastonia',
			'Goldsboro',
			'Greensboro',
			'Greenville',
			'Halifax',
			'Henderson',
			'Hickory',
			'High Point',
			'Hillsborough',
			'Jacksonville',
			'Kinston',
			'Kitty Hawk',
			'Lumberton',
			'Morehead City',
			'Morganton',
			'Nags Head',
			'New Bern',
			'Pinehurst',
			'Raleigh',
			'Rocky Mount',
			'Salisbury',
			'Shelby',
			'Washington',
			'Wilmington',
			'Wilson',
			'Winston-Salem',
			'North Dakota',
			'Bismarck',
			'Devils Lake',
			'Dickinson',
			'Fargo',
			'Grand Forks',
			'Jamestown',
			'Mandan',
			'Minot',
			'Rugby',
			'Valley City',
			'Wahpeton',
			'Williston',
			'Ohio',
			'Akron',
			'Alliance',
			'Ashtabula',
			'Athens',
			'Barberton',
			'Bedford',
			'Bellefontaine',
			'Bowling Green',
			'Canton',
			'Chillicothe',
			'Cincinnati',
			'Cleveland',
			'Cleveland Heights',
			'Columbus',
			'Conneaut',
			'Cuyahoga Falls',
			'Dayton',
			'Defiance',
			'Delaware',
			'East Cleveland',
			'East Liverpool',
			'Elyria',
			'Euclid',
			'Findlay',
			'Gallipolis',
			'Greenville',
			'Hamilton',
			'Kent',
			'Kettering',
			'Lakewood',
			'Lancaster',
			'Lima',
			'Lorain',
			'Mansfield',
			'Marietta',
			'Marion',
			'Martins Ferry',
			'Massillon',
			'Mentor',
			'Middletown',
			'Milan',
			'Mount Vernon',
			'New Philadelphia',
			'Newark',
			'Niles',
			'North College Hill',
			'Norwalk',
			'Oberlin',
			'Painesville',
			'Parma',
			'Piqua',
			'Portsmouth',
			'Put-in-Bay',
			'Salem',
			'Sandusky',
			'Shaker Heights',
			'Springfield',
			'Steubenville',
			'Tiffin',
			'Toledo',
			'Urbana',
			'Warren',
			'Wooster',
			'Worthington',
			'Xenia',
			'Yellow Springs',
			'Youngstown',
			'Zanesville',
			'Oklahoma',
			'Ada',
			'Altus',
			'Alva',
			'Anadarko',
			'Ardmore',
			'Bartlesville',
			'Bethany',
			'Chickasha',
			'Claremore',
			'Clinton',
			'Cushing',
			'Duncan',
			'Durant',
			'Edmond',
			'El Reno',
			'Elk City',
			'Enid',
			'Eufaula',
			'Frederick',
			'Guthrie',
			'Guymon',
			'Hobart',
			'Holdenville',
			'Hugo',
			'Lawton',
			'McAlester',
			'Miami',
			'Midwest City',
			'Moore',
			'Muskogee',
			'Norman',
			'Oklahoma City',
			'Okmulgee',
			'Pauls Valley',
			'Pawhuska',
			'Perry',
			'Ponca City',
			'Pryor',
			'Sallisaw',
			'Sand Springs',
			'Sapulpa',
			'Seminole',
			'Shawnee',
			'Stillwater',
			'Tahlequah',
			'The Village',
			'Tulsa',
			'Vinita',
			'Wewoka',
			'Woodward',
			'Oregon',
			'Albany',
			'Ashland',
			'Astoria',
			'Baker City',
			'Beaverton',
			'Bend',
			'Brookings',
			'Burns',
			'Coos Bay',
			'Corvallis',
			'Eugene',
			'Grants Pass',
			'Hillsboro',
			'Hood River',
			'Jacksonville',
			'John Day',
			'Klamath Falls',
			'La Grande',
			'Lake Oswego',
			'Lakeview',
			'McMinnville',
			'Medford',
			'Newberg',
			'Newport',
			'Ontario',
			'Oregon City',
			'Pendleton',
			'Port Orford',
			'Portland',
			'Prineville',
			'Redmond',
			'Reedsport',
			'Roseburg',
			'Salem',
			'Seaside',
			'Springfield',
			'The Dalles',
			'Tillamook',
			'Pennsylvania',
			'Abington',
			'Aliquippa',
			'Allentown',
			'Altoona',
			'Ambridge',
			'Bedford',
			'Bethlehem',
			'Bloomsburg',
			'Bradford',
			'Bristol',
			'Carbondale',
			'Carlisle',
			'Chambersburg',
			'Chester',
			'Columbia',
			'Easton',
			'Erie',
			'Franklin',
			'Germantown',
			'Gettysburg',
			'Greensburg',
			'Hanover',
			'Harmony',
			'Harrisburg',
			'Hazleton',
			'Hershey',
			'Homestead',
			'Honesdale',
			'Indiana',
			'Jeannette',
			'Jim Thorpe',
			'Johnstown',
			'Lancaster',
			'Lebanon',
			'Levittown',
			'Lewistown',
			'Lock Haven',
			'Lower Southampton',
			'McKeesport',
			'Meadville',
			'Middletown',
			'Monroeville',
			'Nanticoke',
			'New Castle',
			'New Hope',
			'New Kensington',
			'Norristown',
			'Oil City',
			'Philadelphia',
			'Phoenixville',
			'Pittsburgh',
			'Pottstown',
			'Pottsville',
			'Reading',
			'Scranton',
			'Shamokin',
			'Sharon',
			'State College',
			'Stroudsburg',
			'Sunbury',
			'Swarthmore',
			'Tamaqua',
			'Titusville',
			'Uniontown',
			'Warren',
			'Washington',
			'West Chester',
			'Wilkes-Barre',
			'Williamsport',
			'York',
			'Rhode Island',
			'Barrington',
			'Bristol',
			'Central Falls',
			'Cranston',
			'East Greenwich',
			'East Providence',
			'Kingston',
			'Middletown',
			'Narragansett',
			'Newport',
			'North Kingstown',
			'Pawtucket',
			'Portsmouth',
			'Providence',
			'South Kingstown',
			'Tiverton',
			'Warren',
			'Warwick',
			'Westerly',
			'Wickford',
			'Woonsocket',
			'South Carolina',
			'Abbeville',
			'Aiken',
			'Anderson',
			'Beaufort',
			'Camden',
			'Charleston',
			'Columbia',
			'Darlington',
			'Florence',
			'Gaffney',
			'Georgetown',
			'Greenville',
			'Greenwood',
			'Hartsville',
			'Lancaster',
			'Mount Pleasant',
			'Myrtle Beach',
			'Orangeburg',
			'Rock Hill',
			'Spartanburg',
			'Sumter',
			'Union',
			'South Dakota',
			'Aberdeen',
			'Belle Fourche',
			'Brookings',
			'Canton',
			'Custer',
			'De Smet',
			'Deadwood',
			'Hot Springs',
			'Huron',
			'Lead',
			'Madison',
			'Milbank',
			'Mitchell',
			'Mobridge',
			'Pierre',
			'Rapid City',
			'Sioux Falls',
			'Spearfish',
			'Sturgis',
			'Vermillion',
			'Watertown',
			'Yankton',
			'Tennessee',
			'Alcoa',
			'Athens',
			'Chattanooga',
			'Clarksville',
			'Cleveland',
			'Columbia',
			'Cookeville',
			'Dayton',
			'Elizabethton',
			'Franklin',
			'Gallatin',
			'Gatlinburg',
			'Greeneville',
			'Jackson',
			'Johnson City',
			'Jonesborough',
			'Kingsport',
			'Knoxville',
			'Lebanon',
			'Maryville',
			'Memphis',
			'Morristown',
			'Murfreesboro',
			'Nashville',
			'Norris',
			'Oak Ridge',
			'Shelbyville',
			'Tullahoma',
			'Texas',
			'Abilene',
			'Alpine',
			'Amarillo',
			'Arlington',
			'Austin',
			'Baytown',
			'Beaumont',
			'Big Spring',
			'Borger',
			'Brownsville',
			'Bryan',
			'Canyon',
			'Cleburne',
			'College Station',
			'Corpus Christi',
			'Crystal City',
			'Dallas',
			'Del Rio',
			'Denison',
			'Denton',
			'Eagle Pass',
			'Edinburg',
			'El Paso',
			'Fort Worth',
			'Freeport',
			'Galveston',
			'Garland',
			'Goliad',
			'Greenville',
			'Harlingen',
			'Houston',
			'Huntsville',
			'Irving',
			'Johnson City',
			'Kilgore',
			'Killeen',
			'Kingsville',
			'Laredo',
			'Longview',
			'Lubbock',
			'Lufkin',
			'Marshall',
			'McAllen',
			'McKinney',
			'Mesquite',
			'Midland',
			'Mission',
			'Nacogdoches',
			'New Braunfels',
			'Odessa',
			'Orange',
			'Pampa',
			'Paris',
			'Pasadena',
			'Pecos',
			'Pharr',
			'Plainview',
			'Plano',
			'Port Arthur',
			'Port Lavaca',
			'Richardson',
			'San Angelo',
			'San Antonio',
			'San Felipe',
			'San Marcos',
			'Sherman',
			'Sweetwater',
			'Temple',
			'Texarkana',
			'Texas City',
			'Tyler',
			'Uvalde',
			'Victoria',
			'Waco',
			'Weatherford',
			'Wichita Falls',
			'Ysleta',
			'Utah',
			'Alta',
			'American Fork',
			'Bountiful',
			'Brigham City',
			'Cedar City',
			'Clearfield',
			'Delta',
			'Fillmore',
			'Green River',
			'Heber City',
			'Kanab',
			'Layton',
			'Lehi',
			'Logan',
			'Manti',
			'Moab',
			'Monticello',
			'Murray',
			'Nephi',
			'Ogden',
			'Orderville',
			'Orem',
			'Panguitch',
			'Park City',
			'Payson',
			'Price',
			'Provo',
			'Saint George',
			'Salt Lake City',
			'Spanish Fork',
			'Springville',
			'Tooele',
			'Vernal',
			'Vermont',
			'Barre',
			'Bellows Falls',
			'Bennington',
			'Brattleboro',
			'Burlington',
			'Essex',
			'Manchester',
			'Middlebury',
			'Montpelier',
			'Newport',
			'Plymouth',
			'Rutland',
			'Saint Albans',
			'Saint Johnsbury',
			'Sharon',
			'Winooski',
			'Virginia',
			'Abingdon',
			'Alexandria',
			'Bristol',
			'Charlottesville',
			'Chesapeake',
			'Danville',
			'Fairfax',
			'Falls Church',
			'Fredericksburg',
			'Hampton',
			'Hanover',
			'Hopewell',
			'Lexington',
			'Lynchburg',
			'Manassas',
			'Martinsville',
			'New Market',
			'Newport News',
			'Norfolk',
			'Petersburg',
			'Portsmouth',
			'Reston',
			'Richmond',
			'Roanoke',
			'Staunton',
			'Suffolk',
			'Virginia Beach',
			'Waynesboro',
			'Williamsburg',
			'Winchester',
			'Washington',
			'Aberdeen',
			'Anacortes',
			'Auburn',
			'Bellevue',
			'Bellingham',
			'Bremerton',
			'Centralia',
			'Coulee Dam',
			'Coupeville',
			'Ellensburg',
			'Ephrata',
			'Everett',
			'Hoquiam',
			'Kelso',
			'Kennewick',
			'Longview',
			'Moses Lake',
			'Oak Harbor',
			'Olympia',
			'Pasco',
			'Point Roberts',
			'Port Angeles',
			'Pullman',
			'Puyallup',
			'Redmond',
			'Renton',
			'Richland',
			'Seattle',
			'Spokane',
			'Tacoma',
			'Vancouver',
			'Walla Walla',
			'Wenatchee',
			'Yakima',
			'West Virginia',
			'Bath',
			'Beckley',
			'Bluefield',
			'Buckhannon',
			'Charles Town',
			'Charleston',
			'Clarksburg',
			'Elkins',
			'Fairmont',
			'Grafton',
			'Harpers Ferry',
			'Hillsboro',
			'Hinton',
			'Huntington',
			'Keyser',
			'Lewisburg',
			'Logan',
			'Martinsburg',
			'Morgantown',
			'Moundsville',
			'New Martinsville',
			'Parkersburg',
			'Philippi',
			'Point Pleasant',
			'Princeton',
			'Romney',
			'Shepherdstown',
			'South Charleston',
			'Summersville',
			'Weirton',
			'Welch',
			'Wellsburg',
			'Weston',
			'Wheeling',
			'White Sulphur Springs',
			'Williamson',
			'Wisconsin',
			'Appleton',
			'Ashland',
			'Baraboo',
			'Belmont',
			'Beloit',
			'Eau Claire',
			'Fond du Lac',
			'Green Bay',
			'Hayward',
			'Janesville',
			'Kenosha',
			'La Crosse',
			'Lake Geneva',
			'Madison',
			'Manitowoc',
			'Marinette',
			'Menasha',
			'Milwaukee',
			'Neenah',
			'New Glarus',
			'Oconto',
			'Oshkosh',
			'Peshtigo',
			'Portage',
			'Prairie du Chien',
			'Racine',
			'Rhinelander',
			'Ripon',
			'Sheboygan',
			'Spring Green',
			'Stevens Point',
			'Sturgeon Bay',
			'Superior',
			'Waukesha',
			'Wausau',
			'Wauwatosa',
			'West Allis',
			'West Bend',
			'Wisconsin Dells',
			'Wyoming',
			'Buffalo',
			'Casper',
			'Cheyenne',
			'Cody',
			'Douglas',
			'Evanston',
			'Gillette',
			'Green River',
			'Jackson',
			'Lander',
			'Laramie',
			'Newcastle',
			'Powell',
			'Rawlins',
			'Riverton',
			'Rock Springs',
			'Sheridan',
			'Ten Sleep',
			'Thermopolis',
			'Torrington',
			'Worland',
		];
		$unis = [
			'Massachusetts Institute of Technology (MIT)',
			'Stanford University',
			'Harvard University',
			'California Institute of Technology (Caltech)',
			'University of Chicago',
			'Princeton University',
			'Cornell University',
			'Yale University',
			'Johns Hopkins University',
			'Columbia University',
			'University of Pennsylvania',
			'University of Michigan',
			'Duke University',
			'University of California, Berkeley (UCB)',
			'Northwestern University',
			'University of California, Los Angeles (UCLA)',
			'University of California, San Diego (UCSD)',
			'Carnegie Mellon University',
			'New York University',
			'Brown University',
			'University of Wisconsin-Madison',
			'University of Washington',
			'University of Texas at Austin',
			'University of Illinois at Urbana-Champaign',
			'Georgia Institute of Technology',
			'University of North Carolina, Chapel Hill',
			'Boston University',
			'The Ohio State University',
			'Rice University',
			'Pennsylvania State University',
			'Washington University in St. Louis',
			'Purdue University',
			'University of California, Davis',
			'University of Maryland, College Park',
			'University of Southern California',
			'University of California, Santa Barbara (UCSB)',
			'University of Pittsburgh',
			'Emory University',
			'Michigan State University',
			'University of Minnesota',
			'University of California, Irvine',
			'Dartmouth College ',
			'University of Virginia',
			'University of Florida',
			'University of Colorado Boulder',
			'University of Rochester',
			'Texas A&M University',
			'University of Illinois, Chicago (UIC)',
			'Arizona State University',
			'Vanderbilt University',
			'Case Western Reserve University',
			'University of Notre Dame',
			'Georgetown University ',
			'The University of Arizona',
			'Tufts University',
			'University of Massachusetts Amherst',
			'University of Miami',
			'North Carolina State University',
			'Rutgers University - New Brunswick',
			'University of California, Santa Cruz',
			'Indiana University Bloomington',
			'University at Buffalo SUNY',
			'University of California, Riverside',
			'The Katz School at Yeshiva University',
			'Boston College',
			'University of Hawaii at Mañoa',
			'Northeastern University',
			'George Washington University',
			'Rensselaer Polytechnic University',
			'Virginia Polytechnic Institute and State University',
			'Stony Brook University, State University of New York',
			'University of Kansas',
			'University of Utah',
			'University of Colorado, Denver',
			'Illinois Institute of Technology',
			'Washington State University',
			'Brandeis University',
			'Wake Forest University',
			'The University of Georgia',
			'University of Connecticut',
			'University of Delaware',
			'University of Iowa',
			'University of Texas Dallas ',
			'Florida State University',
			'Oregon State University',
			'Tulane University',
			'The University of Tennessee, Knoxville',
			'University of New Mexico',
			'Wayne State University',
			'American University',
			'Iowa State University',
			'Colorado State University',
			'University of Maryland, Baltimore County',
			'City University of New York',
			'Clark University ',
			'Drexel University',
			'Lehigh University',
			'Syracuse University',
			'University of Cincinnati',
			'University of Nebraska-Lincoln',
			'University of Oklahoma',
			'University of South Florida',
		];
		$grades = [
			'A+',
			'A',
			'A-',
			'B+',
			'B',
			'B-',
			'C+',
			'C',
			'C-',
			'D+',
			'D',
			'F',
		];
		$majors = [
			'Accounting',
			'Actuarial Science',
			'Advertising',
			'Agriculture',
			'Agricultural and Biological Engineering',
			'Agricultural Business Management',
			'Agriculture Economics',
			'Animal Bioscience',
			'Animal Sciences',
			'Anthropology',
			'Applied Mathematics',
			'Archaeology',
			'Architectural Engineering',
			'Architecture',
			'Art History',
			'Studio Art',
			'Art Education',
			'Biobehavioral Health',
			'Biochemistry',
			'Bioengineering',
			'Biology',
			'Biophysics',
			'Biotechnology',
			'Business Administration and Management',
			'Business Logistics',
			'Chemical Engineering',
			'Chemistry',
			'Children',
			'Civil Engineering',
			'Computer Engineering',
			'Computer Science',
			'Crime, Law, and Justice',
			'Dance',
			'Earth Sciences',
			'Economics',
			'Electrical Engineering',
			'Elementary and Kindergarten Education',
			'Engineering Science',
			'English',
			'Environmental Systems Engineering',
			'Environmental Sciences',
			'Environmental Resource Management',
			'Film and Video',
			'Finance',
			'Food Science',
			'Forest Science',
			'Forest Technology',
			'General Science',
			'Geography',
			'Geosciences',
			'Graphic Design and Photography',
			'Health and Physical Education',
			'Health Policy and Administration',
			'History',
			'Horticulture',
			'Hotel, Restaurant, and Institutional Management',
			'Human Development and Family Studies',
			'Individual and Family Studies',
			'Industrial Engineering',
			'Information Sciences and Technology',
			'Journalism',
			'Kinesiology',
			'Landscape Architecture',
			'Law Enforcement and Correction',
			'Marine Biology',
			'Marketing',
			'Mathematics',
			'Mechanical Engineering',
			'Media Studies',
			'Meteorology',
			'Microbiology',
			'Mineral Economics',
			'Modern Languages',
			'Music Education',
			'Nuclear Engineering',
			'Nursing',
			'Nutrition',
			'Philosophy',
			'Physics',
			'Physiology',
			'Political Science',
			'Pre-medicine',
			'Psychology',
			'Public Relations',
			'Real Estate',
			'Recreation and Parks',
			'Rehabilitation Services',
			'Religious Studies',
			'Secondary Education',
			'Sociology',
			'Social Work',
			'Special Education',
			'Speech Communication',
			'Speech Pathology and Audiology/Communication Disorder',
			'Statistics',
			'Telecommunications',
			'Theater',
			'Wildlife and Fishery Science',
			'Wildlife Technology',
			'Womens Studies',
		];
		//Addresses init($study_at, $study_what, $study_since, $study_to, $grade, $user)
		foreach ($users as $user) {
			if ($user->addresses()->count() < 3) {
				$co = $countries[rand(0, count($countries) - 1)];
				$st = $states[rand(0, count($states) - 1)];
				$ci = $cities[rand(0, count($cities) - 1)];
				$add = new UserAddress();
				$add->init(json_encode(array('user' => $user->id, 'country' => $co, 'state' => $st, 'region' => $ci, 'index' => json_encode(array()))));
			}
			if ($user->age() > 23) {
				$u = $unis[rand(0, count($unis) - 1)];
				$g = $grades[rand(0, count($grades) - 1)];
				$m = $majors[rand(0, count($majors) - 1)];
				$hd = new High_education();
				$hd->init($u, $m, $user->birthYear() + 18 . '-10-01', $user->birthYear() + 22 . '-06-01', $g, $user->id);
			}
		}

		return 'done';

	}

	public function addUsersPatch(Request $request) {
		$usersCount = User::all()->count();
		$names = [
			'Liam',
			'Noah',
			'William',
			'James',
			'Logan',
			'Benjamin',
			'Mason',
			'Elijah',
			'Oliver',
			'Jacob',
			'Lucas',
			'Michael',
			'Alexander',
			'Ethan',
			'Daniel',
			'Matthew',
			'Aiden',
			'Henry',
			'Joseph',
			'Jackson',
			'Samuel',
			'Sebastian',
			'David',
			'Carter',
			'Wyatt',
			'Jayden',
			'John',
			'Owen',
			'Dylan',
			'Luke',
			'Gabriel',
			'Anthony',
			'Isaac',
			'Grayson',
			'Jack',
			'Julian',
			'Levi',
			'Christopher',
			'Joshua',
			'Andrew',
			'Lincoln',
			'Mateo',
			'Ryan',
			'Jaxon',
			'Nathan',
			'Aaron',
			'Isaiah',
			'Thomas',
			'Charles',
			'Caleb',
			'Josiah',
			'Christian',
			'Hunter',
			'Eli',
			'Jonathan',
			'Connor',
			'Landon',
			'Adrian',
			'Asher',
			'Cameron',
			'Leo',
			'Theodore',
			'Jeremiah',
			'Hudson',
			'Robert',
			'Easton',
			'Nolan',
			'Nicholas',
			'Ezra',
			'Colton',
			'Angel',
			'Brayden',
			'Jordan',
			'Dominic',
			'Austin',
			'Ian',
			'Adam',
			'Elias',
			'Jaxson',
			'Greyson',
			'Jose',
			'Ezekiel',
			'Carson',
			'Evan',
			'Maverick',
			'Bryson',
			'Jace',
			'Cooper',
			'Xavier',
			'Parker',
			'Roman',
			'Jason',
			'Santiago',
			'Chase',
			'Sawyer',
			'Gavin',
			'Leonardo',
			'Kayden',
			'Ayden',
			'Jameson',
			'Kevin',
			'Bentley',
			'Zachary',
			'Everett',
			'Axel',
			'Tyler',
			'Micah',
			'Vincent',
			'Weston',
			'Miles',
			'Wesley',
			'Nathaniel',
			'Harrison',
			'Brandon',
			'Cole',
			'Declan',
			'Luis',
			'Braxton',
			'Damian',
			'Silas',
			'Tristan',
			'Ryder',
			'Bennett',
			'George',
			'Emmett',
			'Justin',
			'Kai',
			'Max',
			'Diego',
			'Luca',
			'Ryker',
			'Carlos',
			'Maxwell',
			'Kingston',
			'Ivan',
			'Maddox',
			'Juan',
			'Ashton',
			'Jayce',
			'Rowan',
			'Kaiden',
			'Giovanni',
			'Eric',
			'Jesus',
			'Calvin',
			'Abel',
			'King',
			'Camden',
			'Amir',
			'Blake',
			'Alex',
			'Brody',
			'Malachi',
			'Emmanuel',
			'Jonah',
			'Beau',
			'Jude',
			'Antonio',
			'Alan',
			'Elliott',
			'Elliot',
			'Waylon',
			'Xander',
			'Timothy',
			'Victor',
			'Bryce',
			'Finn',
			'Brantley',
			'Edward',
			'Abraham',
			'Patrick',
			'Grant',
			'Karter',
			'Hayden',
			'Richard',
			'Miguel',
			'Joel',
			'Gael',
			'Tucker',
			'Rhett',
			'Avery',
			'Steven',
			'Graham',
			'Kaleb',
			'Jasper',
			'Jesse',
			'Matteo',
			'Dean',
			'Zayden',
			'Preston',
			'August',
			'Oscar',
			'Jeremy',
			'Alejandro',
			'Marcus',
			'Dawson',
			'Lorenzo',
			'Messiah',
			'Zion',
			'Maximus',
			'River',
			'Zane',
			'Mark',
			'Brooks',
			'Nicolas',
			'Paxton',
			'Judah',
			'Emiliano',
			'Kaden',
			'Bryan',
			'Kyle',
			'Myles',
			'Peter',
			'Charlie',
			'Kyrie',
			'Thiago',
			'Brian',
			'Kenneth',
			'Andres',
			'Lukas',
			'Aidan',
			'Jax',
			'Caden',
			'Milo',
			'Paul',
			'Beckett',
			'Brady',
			'Colin',
			'Omar',
			'Bradley',
			'Javier',
			'Knox',
			'Jaden',
			'Barrett',
			'Israel',
			'Matias',
			'Jorge',
			'Zander',
			'Derek',
			'Josue',
			'Cayden',
			'Holden',
			'Griffin',
			'Arthur',
			'Leon',
			'Felix',
			'Remington',
			'Jake',
			'Killian',
			'Clayton',
			'Sean',
			'Adriel',
			'Riley',
			'Archer',
			'Legend',
			'Erick',
			'Enzo',
			'Corbin',
			'Francisco',
			'Dallas',
			'Emilio',
			'Gunner',
			'Simon',
			'Andre',
			'Walter',
			'Damien',
			'Chance',
			'Phoenix',
			'Colt',
			'Tanner',
			'Stephen',
			'Kameron',
			'Tobias',
			'Manuel',
			'Amari',
			'Emerson',
			'Louis',
			'Cody',
			'Finley',
			'Iker',
			'Martin',
			'Rafael',
			'Nash',
			'Beckham',
			'Cash',
			'Karson',
			'Rylan',
			'Reid',
			'Theo',
			'Ace',
			'Eduardo',
			'Spencer',
			'Raymond',
			'Maximiliano',
			'Anderson',
			'Ronan',
			'Lane',
			'Cristian',
			'Titus',
			'Travis',
			'Jett',
			'Ricardo',
			'Bodhi',
			'Gideon',
			'Jaiden',
			'Fernando',
			'Mario',
			'Conor',
			'Keegan',
			'Ali',
			'Cesar',
			'Ellis',
			'Jayceon',
			'Walker',
			'Cohen',
			'Arlo',
			'Hector',
			'Dante',
			'Kyler',
			'Garrett',
			'Donovan',
			'Seth',
			'Jeffrey',
			'Tyson',
			'Jase',
			'Desmond',
			'Caiden',
			'Gage',
			'Atlas',
			'Major',
			'Devin',
			'Edwin',
			'Angelo',
			'Orion',
			'Conner',
			'Julius',
			'Marco',
			'Jensen',
			'Daxton',
			'Peyton',
			'Zayn',
			'Collin',
			'Jaylen',
			'Dakota',
			'Prince',
			'Johnny',
			'Kayson',
			'Cruz',
			'Hendrix',
			'Atticus',
			'Troy',
			'Kane',
			'Edgar',
			'Sergio',
			'Kash',
			'Marshall',
			'Johnathan',
			'Romeo',
			'Shane',
			'Warren',
			'Joaquin',
			'Wade',
			'Leonel',
			'Trevor',
			'Dominick',
			'Muhammad',
			'Erik',
			'Odin',
			'Quinn',
			'Jaxton',
			'Dalton',
			'Nehemiah',
			'Frank',
			'Grady',
			'Gregory',
			'Andy',
			'Solomon',
			'Malik',
			'Rory',
			'Clark',
			'Reed',
			'Harvey',
			'Zayne',
			'Jay',
			'Jared',
			'Noel',
			'Shawn',
			'Fabian',
			'Ibrahim',
			'Adonis',
			'Ismael',
			'Pedro',
			'Leland',
			'Malakai',
			'Malcolm',
			'Alexis',
			'Kason',
			'Porter',
			'Sullivan',
			'Raiden',
			'Allen',
			'Ari',
			'Russell',
			'Princeton',
			'Winston',
			'Kendrick',
			'Roberto',
			'Lennox',
			'Hayes',
			'Finnegan',
			'Nasir',
			'Kade',
			'Nico',
			'Emanuel',
			'Landen',
			'Moises',
			'Ruben',
			'Hugo',
			'Abram',
			'Adan',
			'Khalil',
			'Zaiden',
			'Augustus',
			'Marcos',
			'Philip',
			'Phillip',
			'Cyrus',
			'Esteban',
			'Braylen',
			'Albert',
			'Bruce',
			'Kamden',
			'Lawson',
			'Jamison',
			'Sterling',
			'Damon',
			'Gunnar',
			'Kyson',
			'Luka',
			'Franklin',
			'Ezequiel',
			'Pablo',
			'Derrick',
			'Zachariah',
			'Cade',
			'Jonas',
			'Dexter',
			'Kolton',
			'Remy',
			'Hank',
			'Tate',
			'Trenton',
			'Kian',
			'Drew',
			'Mohamed',
			'Dax',
			'Rocco',
			'Bowen',
			'Mathias',
			'Ronald',
			'Francis',
			'Matthias',
			'Milan',
			'Maximilian',
			'Royce',
			'Skyler',
			'Corey',
			'Kasen',
			'Drake',
			'Gerardo',
			'Jayson',
			'Sage',
			'Braylon',
			'Benson',
			'Moses',
			'Alijah',
			'Rhys',
			'Otto',
			'Oakley',
			'Armando',
			'Jaime',
			'Nixon',
			'Saul',
			'Scott',
			'Brycen',
			'Ariel',
			'Enrique',
			'Donald',
			'Chandler',
			'Asa',
			'Eden',
			'Davis',
			'Keith',
			'Frederick',
			'Rowen',
			'Lawrence',
			'Leonidas',
			'Aden',
			'Julio',
			'Darius',
			'Johan',
			'Deacon',
			'Cason',
			'Danny',
			'Nikolai',
			'Taylor',
			'Alec',
			'Royal',
			'Armani',
			'Kieran',
			'Luciano',
			'Omari',
			'Rodrigo',
			'Arjun',
			'Ahmed',
			'Brendan',
			'Cullen',
			'Raul',
			'Raphael',
			'Ronin',
			'Brock',
			'Pierce',
			'Alonzo',
			'Casey',
			'Dillon',
			'Uriel',
			'Dustin',
			'Gianni',
			'Roland',
			'Landyn',
			'Kobe',
			'Dorian',
			'Emmitt',
			'Ryland',
			'Apollo',
			'Aarav',
			'Roy',
			'Duke',
			'Quentin',
			'Sam',
			'Lewis',
			'Tony',
			'Uriah',
			'Dennis',
			'Moshe',
			'Isaias',
			'Braden',
			'Quinton',
			'Cannon',
			'Ayaan',
			'Mathew',
			'Kellan',
			'Niko',
			'Edison',
			'Izaiah',
			'Jerry',
			'Gustavo',
			'Jamari',
			'Marvin',
			'Mauricio',
			'Ahmad',
			'Mohammad',
			'Justice',
			'Trey',
			'Elian',
			'Mohammed',
			'Sincere',
			'Yusuf',
			'Arturo',
			'Callen',
			'Rayan',
			'Keaton',
			'Wilder',
			'Mekhi',
			'Memphis',
			'Cayson',
			'Conrad',
			'Kaison',
			'Kyree',
			'Soren',
			'Colby',
			'Bryant',
			'Lucian',
			'Alfredo',
			'Cassius',
			'Marcelo',
			'Nikolas',
			'Brennan',
			'Darren',
			'Jasiah',
			'Jimmy',
			'Lionel',
			'Reece',
			'Ty',
			'Chris',
			'Forrest',
			'Korbin',
			'Tatum',
			'Jalen',
			'Santino',
			'Case',
			'Leonard',
			'Alvin',
			'Issac',
			'Bo',
			'Quincy',
			'Mack',
			'Samson',
			'Rex',
			'Alberto',
			'Callum',
			'Curtis',
			'Hezekiah',
			'Finnley',
			'Briggs',
			'Kamari',
			'Zeke',
			'Raylan',
			'Neil',
			'Titan',
			'Julien',
			'Kellen',
			'Devon',
			'Kylan',
			'Roger',
			'Axton',
			'Carl',
			'Douglas',
			'Larry',
			'Crosby',
			'Fletcher',
			'Makai',
			'Nelson',
			'Hamza',
			'Lance',
			'Alden',
			'Gary',
			'Wilson',
			'Alessandro',
			'Ares',
			'Kashton',
			'Bruno',
			'Jakob',
			'Stetson',
			'Zain',
			'Cairo',
			'Nathanael',
			'Byron',
			'Harry',
			'Harley',
			'Mitchell',
			'Maurice',
			'Orlando',
			'Kingsley',
			'Kaysen',
			'Sylas',
			'Trent',
			'Ramon',
			'Boston',
			'Lucca',
			'Noe',
			'Jagger',
			'Reyansh',
			'Vihaan',
			'Randy',
			'Thaddeus',
			'Lennon',
			'Kannon',
			'Kohen',
			'Tristen',
			'Valentino',
			'Maxton',
			'Salvador',
			'Abdiel',
			'Langston',
			'Rohan',
			'Kristopher',
			'Yosef',
			'Rayden',
			'Lee',
			'Callan',
			'Tripp',
			'Deandre',
			'Joe',
			'Morgan',
			'Dariel',
			'Colten',
			'Reese',
			'Jedidiah',
			'Ricky',
			'Bronson',
			'Terry',
			'Eddie',
			'Jefferson',
			'Lachlan',
			'Layne',
			'Clay',
			'Madden',
			'Jamir',
			'Tomas',
			'Kareem',
			'Stanley',
			'Brayan',
			'Amos',
			'Kase',
			'Kristian',
			'Clyde',
			'Ernesto',
			'Tommy',
			'Casen',
			'Ford',
			'Crew',
			'Braydon',
			'Brecken',
			'Hassan',
			'Axl',
			'Boone',
			'Leandro',
			'Samir',
			'Jaziel',
			'Magnus',
			'Abdullah',
			'Yousef',
			'Branson',
			'Jadiel',
			'Jaxen',
			'Layton',
			'Franco',
			'Ben',
			'Grey',
			'Kelvin',
			'Chaim',
			'Demetrius',
			'Blaine',
			'Ridge',
			'Colson',
			'Melvin',
			'Anakin',
			'Aryan',
			'Lochlan',
			'Jon',
			'Canaan',
			'Dash',
			'Zechariah',
			'Alonso',
			'Otis',
			'Zaire',
			'Marcel',
			'Brett',
			'Stefan',
			'Aldo',
			'Jeffery',
			'Baylor',
			'Talon',
			'Dominik',
			'Flynn',
			'Carmelo',
			'Dane',
			'Jamal',
			'Kole',
			'Enoch',
			'Graysen',
			'Kye',
			'Vicente',
			'Fisher',
			'Ray',
			'Fox',
			'Jamie',
			'Rey',
			'Zaid',
			'Allan',
			'Emery',
			'Gannon',
			'Joziah',
			'Rodney',
			'Juelz',
			'Sonny',
			'Terrance',
			'Zyaire',
			'Augustine',
			'Cory',
			'Felipe',
			'Aron',
			'Jacoby',
			'Harlan',
			'Marc',
			'Bobby',
			'Joey',
			'Anson',
			'Huxley',
			'Marlon',
			'Anders',
			'Guillermo',
			'Payton',
			'Castiel',
			'Damari',
			'Shepherd',
			'Azariah',
			'Harold',
			'Harper',
			'Henrik',
			'Houston',
			'Kairo',
			'Willie',
			'Elisha',
			'Ameer',
			'Emory',
			'Skylar',
			'Sutton',
			'Alfonso',
			'Brentley',
			'Toby',
			'Blaze',
			'Eugene',
			'Shiloh',
			'Wayne',
			'Darian',
			'Gordon',
			'London',
			'Bodie',
			'Jordy',
			'Jermaine',
			'Denver',
			'Gerald',
			'Merrick',
			'Musa',
			'Vincenzo',
			'Kody',
			'Yahir',
			'Brodie',
			'Trace',
			'Darwin',
			'Tadeo',
			'Bentlee',
			'Billy',
			'Hugh',
			'Reginald',
			'Vance',
			'Westin',
			'Cain',
			'Arian',
			'Dayton',
			'Javion',
			'Terrence',
			'Brysen',
			'Jaxxon',
			'Thatcher',
			'Landry',
			'Rene',
			'Westley',
			'Miller',
			'Alvaro',
			'Cristiano',
			'Eliseo',
			'Ephraim',
			'Adrien',
			'Jerome',
			'Khalid',
			'Aydin',
			'Mayson',
			'Alfred',
			'Duncan',
			'Junior',
			'Kendall',
			'Zavier',
			'Koda',
			'Maison',
			'Caspian',
			'Maxim',
			'Kace',
			'Zackary',
			'Rudy',
			'Coleman',
			'Keagan',
			'Kolten',
			'Maximo',
			'Dario',
			'Davion',
			'Kalel',
			'Briar',
			'Jairo',
			'Misael',
			'Rogelio',
			'Terrell',
			'Heath',
			'Micheal',
			'Wesson',
			'Aaden',
			'Brixton',
			'Draven',
			'Xzavier',
			'Darrell',
			'Keanu',
			'Ronnie',
			'Konnor',
			'Will',
			'Dangelo',
			'Frankie',
			'Kamryn',
			'Salvatore',
			'Santana',
			'Shaun',
			'Coen',
			'Leighton',
			'Mustafa',
			'Reuben',
			'Ayan',
			'Blaise',
			'Dimitri',
			'Keenan',
			'Van',
			'Achilles',
			'Channing',
			'Ishaan',
			'Wells',
			'Benton',
			'Lamar',
			'Nova',
			'Yahya',
			'Dilan',
			'Gibson',
			'Camdyn',
			'Ulises',
			'Alexzander',
			'Valentin',
			'Shepard',
			'Alistair',
			'Eason',
			'Kaiser',
			'Leroy',
			'Zayd',
			'Camilo',
			'Markus',
			'Foster',
			'Davian',
			'Dwayne',
			'Jabari',
			'Judson',
			'Koa',
			'Yehuda',
			'Lyric',
			'Tristian',
			'Agustin',
			'Bridger',
			'Vivaan',
			'Brayson',
			'Emmet',
			'Marley',
			'Mike',
			'Nickolas',
			'Kenny',
			'Leif',
			'Bjorn',
			'Ignacio',
			'Rocky',
			'Chad',
			'Gatlin',
			'Greysen',
			'Kyng',
			'Randall',
			'Reign',
			'Vaughn',
			'Jessie',
			'Louie',
			'Shmuel',
			'Zahir',
			'Ernest',
			'Javon',
			'Khari',
			'Reagan',
			'Avi',
			'Ira',
			'Ledger',
			'Simeon',
			'Yadiel',
			'Maddux',
			'Seamus',
			'Jad',
			'Jeremias',
			'Kylen',
			'Rashad',
			'Santos',
			'Cedric',
			'Craig',
			'Dominique',
			'Gianluca',
			'Jovanni',
			'Bishop',
			'Brenden',
			'Anton',
			'Camron',
			'Giancarlo',
			'Lyle',
			'Alaric',
			'Decker',
			'Eliezer',
			'Ramiro',
			'Yisroel',
			'Howard',
			'Jaxx',
		];
		for ($i = 0; $i < $request->count; $i++) {
			$user = new User();
			$user->initialaize(
				json_encode(array(
					'first_name' => $names[rand(0, count($names) - 1)],
					'last_name' => $names[rand(0, count($names) - 1)],
					'username' => "knockstestuser" . ($i + $usersCount),
					'gender' => "male",
					'middle_name' => $names[rand(0, count($names) - 1)],
					'nickname' => $names[rand(0, count($names) - 1)],
					'birthdate' => rand(1950, 2012) . "-" . rand(1, 12) . "-" . rand(1, 28),
					'email' => "test" . ($i + $usersCount) . "@knocks.com",
					'password' => "testtest12",
					'language' => "en",
				))
			);
		}
		$all = User::where('id', '>', $usersCount)->get();
		$count = $all->count();
		foreach ($all as $one) {
			for ($j = 0; $j < 30; $j++) {
				$c = User::find(rand(0, $count - 1));
				if ($c != null) {
					$one->pairAsFriend($c);
				}

			}
		}
		return "done";
	}
}

?>
